### ISSUE TITLE
请添加konachan.net到fullgfwlist.acl

### ISSUE THREAD

**Issue by hopeuhappy** [ACL4SSR/ACL4SSR#30]
关闭SSR后无法访问，SSR路由设置中使用fullgfwlist.acl文件时也无法访问，使用"绕过局域网和中国大陆"则可以访问。

**Comment by BROBIRD** [comment]
该域名是否已经存在于gfwlist项目中？如果是，请等待本项目更新；如果否，请先向gfwlist项目提交issue。谢谢！

2017年8月28日 20:40，"hopeuhappy" <notifications@github.com>写道：

关闭SSR后无法访问，SSR路由设置中使用fullgfwlist.acl文件时也无法访问，使用"绕过局域网和中国大陆"则可以访问。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ACL4SSR/ACL4SSR/issues/30>, or mute the thread

**Comment by BROBIRD** [comment]
近期将跟进gfwlist，请留意

**Comment by BROBIRD** [comment]
已同步GFWList
