### ISSUE TITLE
现有ACL文件对Android上的Line使用不正常

### ISSUE THREAD

**Issue by hsly109** [ACL4SSR/ACL4SSR#44]
不知道是缺了哪一块，希望现在的maintainer能试试，我自己改动好像也不太能正常使用
另外问一下那个remote dns是怎么写

**Comment by hsly109** [comment]
另请求将ptt.cc加入远程解析，moptt似乎也不正常，不太清楚是怎么回事，对于ptt.cc是属于dns污染

**Comment by BROBIRD** [comment]
Line不能用的话，抓个包试试，或者用wiki里的方法确定一下域名，remote_dns是放在最前面，表示所有解析使用远程DNS解析（对国内CDN不友好）

2017年9月25日 12:08，"hsly109" <notifications@github.com>写道：

不知道是缺了哪一块，希望现在的maintainer能试试，我自己改动好像也不太能正常使用
另外问一下那个remote dns是怎么写

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ACL4SSR/ACL4SSR/issues/44>, or mute the thread

**Comment by hsly109** [comment]
ok 我先试试

**Comment by hsly109** [comment]
fiddler抓不到line的，看不到东西，不知道为什么
但是我根据lhe1的ios版本规则里的line部分，写了一份ACL到规则里，
不知道这样写语法上对不对，特别是remote dns部分，在remote dns和proxy list都弄了一份

这份ACL的测试结果，Line的Android别人测试结果是可以用，我自己拿一部没有安装过Line的测试了一下，也可以正常使用，moptt暂时不太知道具体情况
![p1](https://user-images.githubusercontent.com/22544628/30793299-85f5dc7e-a1f3-11e7-9537-5af6f574dfe9.png)
![p2](https://user-images.githubusercontent.com/22544628/30793300-860a5c30-a1f3-11e7-8413-275c5197dd5d.png)

**Comment by BROBIRD** [comment]
最新版尝试修复，您试一下
